## <a name="markdown100"></a> Indice Numpy:
[Numpy](#markdown1)

[¿Por qué Pandas?](#markdown2)

[Formas de importarlas:](#markdown3)

[Slicing List](#markdown0)

[ Sclicing Matrix:](#markdown4)

[Tipos de datos](#markdown5)

[Dimensiones en los datos](#markdown6)

[Agregar o Eliminar dimensiones](#markdown7)

[Expandir dimensiones](#markdown8)

[Remover/comprimir las dimensiones que no están siendo usadas.](#markdown9)

[Creando Arrays con **NumPy**](#markdown10)

[Creando listas solo con ceros](#markdown11)

[Creando Matrices solo con ceros](#markdown12)

[Creando Matrices solo con unos.](#markdown13)

[Creando listas con valores equidistantes entre ellos](#markdown14)

[Matríz Identidad](#markdown15)

[Valores Aleatoreos "un valor"](#markdown16)

[Valores Aleatoreos "una lista de valores"](#markdown17)

[Valores Aleatoreos "una matriz de valores"](#markdown18)

[Valores Aleatoreos "Enteros"](#markdown19)

[Shape](#markdown20)

[Reshape](#markdown21)

[Funciones Principales de NumPy](#markdown22)

[Devuelve el máx número por columna](#markdown23)

[Devuelve el máx número por fila](#markdown24)

[ptp(), pico a pico](#markdown25)

[Percentile()](#markdown26)

[sort()](#markdown27)

[median()](#markdown28)

[median() con Matrices](#markdown29)

[Desviación std()](#markdown30)

[Varianza var()](#markdown31)

[La Media mean()](#markdown32)

[Concatenar concatenate()](#markdown33)

[Transpuesta](#markdown34)

[copy()](#markdown35)

[Condiciones](#markdown36)

[Operaciones](#markdown37)

[Producto entre Matrices](#markdown38)

## <a name="markdown1000"></a> Indice Pandas:

[Series](#markdown39)

[Creando lista con índices específicos](#markdown40)

[Creando una structura matricial con diccionarios](#markdown41)

# Numpy
* Cálculo numérico
* Manejo de Arrays.

# pandas:
* Manipulación y análisis de datos.
# <a name="markdown1"></a> ¿Por qué Numpy?
* Es una librería enfocada al cálculo numérico y manejo de Arrays.

* Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
* Optimiza el almacenamiento en memoria.
* Maneja distintos tipos de datos.
* Es una librería muy poderosa, se pueden crear redes neuronales desde cero.

# <a name="markdown2"></a> ¿Por qué Pandas?
* Pandas está enfocada a la manipulación y análisis de datos.

* Al estar construido sobre NumPy es veloz.
* Requiere poco código para manipular los datos.
* Soporta múltiples formatos de archivos.
* Ordena los datos en una alienación inteligente.
* Se pueden manejar grandes cantidades de datos, hacer analítica y generar dashboards.
* Anilisis inteligente.

#### El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

# <a name="markdown3"></a> Formas de importarlas:
[Indice](#markdown100)

In [1]:
import numpy as np
import pandas as pd

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]

#Volvemos nuestra lista, un array
arr = np.array(lista)

In [2]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)

In [3]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### <a name="markdown0"></a> Slicing List
[Indice](#markdown100)

In [12]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista = np.array(lista)
print(lista[1:6])
print(lista[:6])
print(lista[2:])
print(lista[::3])
print(lista[-1])
print(lista[-3])

[2 3 4 5 6]
[1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[1 4 7]
9
7


### <a name="markdown4"></a>  Sclicing Matrix:
[Indice](#markdown100)

In [16]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix)
print(matrix)
print("*"*15)
print(matrix[1:]) #Desde la fila 1 en adelante.
print("*"*15)
print(matrix[1:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
[[4 5 6]
 [7 8 9]]
***************
[[4 5]
 [7 8]]


* **matrix[fila, columna]** --> devuelve el valor en esa fila intersección esa columna

### <a name="markdown5"></a> Tipos de datos
### [Tipos de datos numpy](https://numpy.org/doc/stable/user/basics.types.html):
[Indice](#markdown100)

In [17]:
arr = np.array([1, 2, 3, 4])
arr.dtype #Muestra el tipo de dato de los componenetes de array.

dtype('int64')

In [18]:
arr = np.array([1, 2, 3, 4], dtype='float64') #Cambiamos el tipo de dato!!!
arr.dtype

dtype('float64')

In [20]:
arr = np.array([1, 2, 3, 4]) # type int64
arr = arr.astype(np.float64) # otra forma de cambiar el tipo de dato.
arr.dtype

dtype('float64')

* En términos de resultado final, no hay diferencia entre las dos formas de cambiar el tipo de datos de un arreglo NumPy. Ambas líneas de código logran el mismo resultado: cambiar el tipo de datos del arreglo arr a float64.

* La diferencia radica en el enfoque utilizado para realizar la conversión:

* En la primera línea de código, se especifica el tipo de datos deseado directamente al crear el arreglo mediante el argumento dtype='float64'. Esto significa que el arreglo se crea inicialmente con el tipo de datos especificado.

* En la segunda línea de código, se utiliza el método astype() de NumPy para realizar la conversión explícita del tipo de datos del arreglo. El método astype() toma como argumento el tipo de datos al que se desea convertir el arreglo.
También se podría definir como sigue:
```python
arr = [1, 2, 3, 4]
arr = np.array(arr, dtype='float64') #Cambiamos el tipo de dato!!!
arr.dtype
```

In [25]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_) #Cambiando a Booleano!!!
arr

array([False,  True,  True,  True,  True])

In [28]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_) #Cambiando a Booleano!!!
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [29]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8) #Cambiando a Booleano!!!
arr

array([0, 1, 2, 3, 4], dtype=int8)

### <a name="markdown6"></a> Dimensiones en los datos:
[Indice](#markdown100)
* **Scalar: 0 Un solo dato o valor --> 2 o "r", un solo valor.**
```python
scalar = np.array(42)
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Vector: Listas de Python --> [1,2,3,4]**
```python
scalar = np.array([1,2,3,4])
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Matriz: Hoja de cálculo --> algo que tenga 2 dimensiones (fila, columna).**
```python
scalar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Tensor: Series de tiempo o Imágenes**
![tensor](https://static.platzi.com/media/articlases/Images/tensor.JPG)
```python
tensor = np.array([
    [
        [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]
    ],
    [
        [13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]
    ]
]) #Matríz 4x3 en la primer posición, matríz 4x3 en la segunda posición.
print(tensor)
tensor.ndim
```
* **Nota, el tensor tiene tres dimensiones**: 
* la primera dimensión corresponde a las dos matrices internas. 
* La segunda dimensión corresponde a las filas de cada matriz.
* La tercera dimensión corresponde a las columnas de cada matriz.

In [13]:
tensor = np.array([
                        [        
                            [
                                [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]
                            ],
                            [
                                [13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]
                            ]
                        ]
                    ]) #Matríz 4x3 en la primer posición, matríz 4x3 en la segunda posición.
print(tensor)
tensor.ndim # Con 4 dimensiones.

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[13 13 15]
   [16 17 18]
   [19 20 21]
   [22 23 24]]]]


4

### <a name="markdown7"></a>  Agregar o eliminar dimensiones
[Indice](#markdown100)
* Se puede definir el número de dimensiones desde la declaración del array

In [16]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

### <a name="markdown8"></a>  Expandir dimensiones
[Indice](#markdown100)
* Se pueden expandir dimensiones a los array ya existentes con expand_dims(). Axis = 0 hace referencia a las filas, mientras que axis = 1 a las columnas.

In [14]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [15]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 1)
print(expand)
expand.ndim 

[[1]
 [2]
 [3]]


2

### <a name="markdown9"></a>  Remover/comprimir las dimensiones que no están siendo usadas.
[Indice](#markdown100)

In [18]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


### <a name="markdown10"></a>  Creando Arrays con **numpy**
[Indice](#markdown100)
* Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

* Este método de NumPy nos permite generar arrays sin definir previamente una lista

In [20]:
# forma tradicional con python.
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
# numpy
list_01 = np.arange(1,10)
print(list_01)
list_02 = np.arange(1,10,2) # De 2 en 2
print(list_02)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### <a name="markdown11"></a>  Creando listas solo con ceros
[Indice](#markdown100)

In [25]:
np.zeros(3)

array([0., 0., 0.])

### <a name="markdown12"></a> Creando Matrices solo con ceros.
[Indice](#markdown100)

In [27]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### <a name="markdown13"></a>  Creando Matrces solo con unos.
[Indice](#markdown100)

In [28]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### <a name="markdown14"></a> Crea listas con valores equidistantes entre ellos.
[Indice](#markdown100)
* Sintaxis:
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
* **start:** Es el valor inicial del rango.
* **stop:** Es el valor final del rango.
* **num:** Es el número de elementos que se generarán en el arreglo. Por defecto es 50.
* **endpoint:** Un valor booleano que indica si el valor final está incluido en el arreglo. Si es True, el valor final está incluido; si es False, el valor final no está incluido. Por defecto es True.
* **retstep:** Un valor booleano que indica si se debe retornar el espaciado entre los valores del arreglo. Si es True, se retorna el arreglo y el espaciado; si es False, solo se retorna el arreglo. Por defecto es False.
* **dtype:** El tipo de dato de los elementos en el arreglo. Por defecto es None, lo que significa que se utilizará el tipo de dato por defecto de NumPy.

In [35]:
values = np.linspace(0,10,num=12, retstep=True)# desde 0 hasta 10 con 12 valores
print(values)

(array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ]), 0.9090909090909091)


### <a name="markdown15"></a>  Matriz identidad
[Indice](#markdown100)
* El comando eye es una función de NumPy que se utiliza para crear una matriz identidad. Una matriz identidad es una matriz cuadrada en la que todos los elementos de la diagonal principal son iguales a 1 y los demás elementos son iguales a 0.

* La sintaxis general de eye es la siguiente:
```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```
* **N:** Es el número de filas de la matriz.
* **M:** (Opcional) Es el número de columnas de la matriz. Si no se especifica, se asume que M=N, por lo que la matriz será cuadrada.
* **k:** (Opcional) Es el desplazamiento de la diagonal principal. Un valor positivo indica una diagonal por encima de la diagonal principal, y un valor negativo indica una diagonal por debajo de la diagonal principal. Por defecto, k=0 y la diagonal principal estará compuesta de unos.
* **dtype:** (Opcional) El tipo de dato de los elementos en la matriz. Por defecto, es un tipo de dato flotante (float).
* **order:** (Opcional) Especifica el orden en que se almacenan los elementos en la matriz. Puede ser 'C' (por filas) o 'F' (por columnas). Por defecto, es 'C'.

In [36]:
matriz_identidad = np.eye(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### <a name="markdown16"></a> Valores Aleatoreos "un valor":
[Indice](#markdown100)

In [37]:
np.random.rand()

0.6507831363398214

### <a name="markdown17"></a> Valores Aleatoreos "una lista de valores":
[Indice](#markdown100)

In [38]:
np.random.rand(4)

array([0.58510919, 0.11935745, 0.40646536, 0.49571867])

### <a name="markdown18"></a> Valores Aleatoreos "una Matríz de valores":
[Indice](#markdown100)

In [39]:
np.random.rand(2,3)

array([[0.56556431, 0.77719616, 0.71526729],
       [0.61868235, 0.6897348 , 0.36030092]])

### <a name="markdown19"></a>  Valores Aleatoreos "Enteros":
[Indice](#markdown100)
```python
numpy.random.randint(low, high=None, size=None, dtype=int)
```
* **low:** es el límite inferior del rango (inclusive).
* **high:** es el límite superior del rango (exclusivo). Si no se proporciona, se asume que es el límite superior y el límite inferior se establece en 0.
* **size:** es la forma o dimensiones del array que se desea generar. Puede ser un número entero para generar un único número aleatorio o una tupla de enteros para generar un array multidimensional. Si no se proporciona, se devuelve un único número entero.
* **dtype:** es el tipo de datos de los elementos generados. Por defecto, se utiliza int.

In [40]:
np.random.randint(1,15)

6

In [41]:
np.random.randint(1,100,(10,10))

array([[44, 73, 76, 79, 83, 57, 42, 51, 41, 55],
       [29, 83, 71, 53, 55, 30, 74, 84, 17, 16],
       [70, 20, 74, 39, 51, 59,  7, 82, 13, 71],
       [25, 79, 36, 90,  1, 24, 61, 16, 75,  2],
       [71, 55, 90, 78, 78, 90, 38, 71, 16, 11],
       [81, 62, 42, 92, 74, 56,  6, 14, 10, 13],
       [72, 11, 98, 57, 26, 76, 64, 90, 36, 39],
       [82, 52, 14, 10, 29, 46, 28, 41, 14, 50],
       [88, 59, 25, 92, 30, 50, 10, 29, 12, 73],
       [14, 74, 36, 35, 62,  3, 82, 15, 16, 38]])

### <a name="markdown20"></a>  Shape:
[Indice](#markdown100)
* Forma del arreglo.

In [44]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape # retorna la forma, en este caso una matríz de 3x2

[[6 2]
 [3 8]
 [3 4]]


(3, 2)

### <a name="markdown21"></a> Reshape:
[Indice](#markdown100)
* Cambia la forma del arreglo.
```python
numpy.reshape(array, newshape, order='C')
```
* **array:** El array original que se desea redimensionar.
* **newshape:** La nueva forma que se desea dar al array. Puede ser especificada como una tupla de enteros o como una lista de enteros separados por comas. Es importante tener en cuenta que la cantidad total de elementos en el array original debe ser igual a la cantidad total de elementos en el nuevo array.
* **order (opcional):** Especifica el orden en que se deben leer los elementos del array original para reorganizarlos en el nuevo array. Los posibles valores son 'C' (orden C-contiguo, por defecto), 'F' (orden Fortran-contiguo), o 'A' (lo ordena según la mejor performance del computador).

#### Nota: los parámetros 'C' y 'F' se refieren al orden en el que los elementos del array original se almacenan en la memoria.

#### 'C' hace referencia al estilo de orden C-contiguo, también conocido como orden de fila principal (row-major order) o almacenamiento en el estilo C. En este orden, los elementos de una matriz bidimensional se almacenan por filas, es decir, los elementos de una misma fila se almacenan de forma contigua en la memoria. Este es el orden por defecto en NumPy.
![C-style contiguous segment](https://static.platzi.com/media/user_upload/Apilar%20por%20filas%20V-ca01870a-aaaf-4bdb-8203-6885bd220f20.jpg)
#### 'F' se refiere al estilo de orden Fortran-contiguo, también conocido como orden de columna principal (column-major order) o almacenamiento en el estilo Fortran. En este orden, los elementos de una matriz bidimensional se almacenan por columnas, es decir, los elementos de una misma columna se almacenan de forma contigua en la memoria.
![Fortran-style contiguous segment](https://static.platzi.com/media/user_upload/Apilar%20por%20Columnas-0b5370fe-2271-4d55-bd10-5b290114678b.jpg)
#### La diferencia entre ambos órdenes radica en cómo se accede a los elementos de la matriz en la memoria. Al trabajar con arrays multidimensionales grandes, el orden de almacenamiento puede afectar el rendimiento y la eficiencia del acceso a los elementos.

#### En la mayoría de los casos, el orden 'C' es utilizado por defecto y es adecuado para la mayoría de las operaciones y algoritmos. Sin embargo, en algunos casos particulares, como cuando se trabaja con operaciones lineales algebraicas o algoritmos específicos que requieren un acceso eficiente por columnas, se puede utilizar el orden 'F'.

#### Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en A.

In [47]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.reshape(1,6) # 1x6, está límitado por la cantidad de valores individuales.

[[3 2]
 [8 5]
 [6 4]]


array([[3, 2, 8, 5, 6, 4]])

In [48]:
np.reshape(arr,(1,6)) #otra forma equivalente y válida.

array([[3, 2, 8, 5, 6, 4]])

In [50]:
np.reshape(arr,(2,3), 'C')

array([[3, 2, 8],
       [5, 6, 4]])

In [51]:
np.reshape(arr,(2,3), 'F')

array([[3, 6, 5],
       [8, 2, 4]])

In [52]:
np.reshape(arr,(2,3), 'A')

array([[3, 2, 8],
       [5, 6, 4]])

### <a name="markdown22"></a> Funciones Principales de NumPy:
[Indice](#markdown100)

In [55]:
arr = np.random.randint(1,20,10)
arr

array([19, 16, 14,  7,  9,  8,  5, 19, 18, 12])

In [56]:
matriz = arr.reshape(2,5)
matriz

array([[19, 16, 14,  7,  9],
       [ 8,  5, 19, 18, 12]])

In [57]:
np.max(arr) #arr.max() también funciona.

19

In [58]:
np.max(matriz) #matriz.max() también funciona.

19

### <a name="markdown23"></a>  Devuelve el máx número por columna.
[Indice](#markdown100)
* matriz.max(0) también funciona.

In [60]:
np.max(matriz, 0) 

array([19, 16, 19, 18, 12])

### <a name="markdown24"></a>  Devuelve el máx número por fila.
[Indice](#markdown100)
* matriz.max(1) también funciona.

In [61]:
np.max(matriz, 1)

array([19, 19])

#### También tenemos .argmax() que nos devuelve la posición del Máx. elemento

In [64]:
arr = np.random.randint(1,20,10)
print(arr)
arr.argmax()

[11  8  5  6  7 12 15  7  8  1]


6

In [67]:
matriz = arr.reshape(2,5)
print(matriz)
matriz.argmax(0)

[[11  8  5  6  7]
 [12 15  7  8  1]]


array([1, 1, 1, 1, 0])

In [68]:
matriz.argmax(1)

array([0, 1])

#### Nota: Funcionamiento contrario remplazando "max" por "min"

### <a name="markdown25"></a> ptp(), pico a pico:
[Indice](#markdown100)
* Devuelve la diferencia entre Máx y Mín.

In [70]:
arr = np.random.randint(1,20,10)
arr

array([16, 14, 14,  6,  3,  6,  8, 14,  5, 18])

In [71]:
arr.ptp()

15

### <a name="markdown26"></a> Percentile()
[Indice](#markdown100)
* La función np.percentile() en NumPy se utiliza para calcular los percentiles de un conjunto de datos. Un percentil es un valor que indica la posición relativa de un dato dentro de un conjunto, es decir, el porcentaje de datos que se encuentran por debajo de ese valor.

* La sintaxis básica de la función np.percentile() es la siguiente:
```python
np.percentile(data, q, axis=None)
```
* **data:** Es el conjunto de datos del cual se desea calcular el percentil.
* **q:** Es el percentil o lista de percentiles que se desean calcular. Puede ser un solo valor o una lista de valores.
* **axis:** Es un parámetro opcional que indica a lo largo de qué eje se deben calcular los percentiles en el caso de arrays multidimensionales. Por defecto, se calculan los percentiles en todo el array.
La función np.percentile() devuelve el valor del percentil o una lista de valores si se pasó una lista de percentiles como parámetro q.

#### Nota: El percentil es una medida de posición usada en estadística que indica, una vez ordenados los datos de menor a mayor, el valor de la variable por debajo del cual se encuentra un porcentaje dado de observaciones en un grupo. Por ejemplo, el percentil 20 es el valor bajo el cual se encuentran el 20 % de las observaciones, y el 80 % restante son mayores.


In [4]:
arr = np.random.randint(1,100,10)
arr

array([82, 46, 42, 97, 89, 81, 49, 38, 93, 27])

In [8]:
percentil = np.percentile(arr,50)
percentil

65.0

In [14]:
arr_01 = [1,2,3,4,5,6,7,8,9,10]

per_0 = np.percentile(arr_01,0)
per_50 = np.percentile(arr_01,50)
per_100 = np.percentile(arr_01,100)
print(per_0, per_50, per_100)

1.0 5.5 10.0


### <a name="markdown27"></a> sort():
[Indice](#markdown100)
* ordena de menor a mayor.
```python
arr = arr.sort()
```

### <a name="markdown28"></a> median():
[Indice](#markdown100)
* Entrega la mediana, el valor que está en la mitad.

In [16]:
arr = np.random.randint(1,100,20)
print(arr)
med = np.median(arr)
print(med)

[14 38 59 13 10 25 24 97 94 57 41 32 41 63 97 93 10 83 97 78]
49.0


### <a name="markdown29"></a> median() con Matrices:
[Indice](#markdown100)

In [23]:
matrix = np.reshape(arr,(2,10))
print(matrix)

med_mat_col = np.median(matrix,0) #Por Columnas.
print(f'by col: {med_mat_col}')

med_mat_row = np.median(matrix,1)
print(f'by row: {med_mat_row}')

[[14 38 59 13 10 25 24 97 94 57]
 [41 32 41 63 97 93 10 83 97 78]]
by col: [27.5 35.  50.  38.  53.5 59.  17.  90.  95.5 67.5]
by row: [31.5 70.5]


### <a name="markdown30"></a> Desviación std():
[Indice](#markdown100)

In [24]:
arr = np.random.randint(1,100,20)
dsta = np.std(arr)
print(dsta)

29.583610327341724


### <a name="markdown31"></a> Varianza var()
[Indice](#markdown100)

In [34]:
arr = np.random.randint(1,100,20)
var = np.var(arr)

#Nota, la var = dsta**2
dsta = np.std(arr)
var_01 = dsta**2 #La varianza = al cuadrado de la desv std.
print(f'var: {var}, dsta: {dsta}, dsta**2: {var_01}')

var: 940.6899999999998, dsta: 30.670670028546812, dsta**2: 940.6899999999997


### <a name="markdown32"></a> La Media mean()
[Indice](#markdown100)
* Es el promedio.
```python
arr = np.mean(arr)
```

### <a name="markdown33"></a> Concatenar concatenate()
[Indice](#markdown100)

In [40]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([5,6]) # Tiene dim: 1
print(b)

[[1 2]
 [3 4]]
[5 6]


#### **Tienen que tener las mismas dimensiones**

In [37]:
b_exp_col = np.expand_dims(b, axis=0)
b_exp_row = np.expand_dims(b, axis=1)

print(b_exp_col, f'dim: {b_exp_col.ndim}')
print(b_exp_row, f'dim: {b_exp_row.ndim}')

[[5 6]] dim: 2
[[5]
 [6]] dim: 2


#### **A concatenar por columnas:**

In [38]:
conc_col = np.concatenate((a,b_exp_col), axis=0)
conc_col

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Concatenamos por filas:

In [43]:
conc_col = np.concatenate((a,b_exp_row), axis=1)
conc_col

array([[1, 2, 5],
       [3, 4, 6]])

### <a name="markdown34"></a> Transpuesta T:
[Indice](#markdown100)
* ejemplo pasa de 3x2 --> 2x3

In [45]:
a = np.array([[1,2],[3,4]])
print(a)
a_transp = a.T
print(a_transp)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Entonces podemos utilizar para concatenar

In [47]:
conc_col = np.concatenate((a,b_exp_col.T), axis=1) #Sin la "T" da error, y nos da igual que b_exp_row
conc_col

array([[1, 2, 5],
       [3, 4, 6]])

### <a name="markdown35"></a> copy():
[Indice](#markdown100)
* Uno de los problemas más comunes es manipular una variable y modificarla, tal como se observa en el siguiente ejemplo.

In [60]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
arr_cuted_01 = arr[0:6]
print(arr_cuted_01)

arr_cuted_01[:] = 0 #todos los valores en 0.
print(arr_cuted_01)

print(arr) #Se ve el cambio a la variable original

[1 2 3 4 5 6]
[0 0 0 0 0 0]
[ 0  0  0  0  0  0  7  8  9 10]


#### Solución a Copy:

In [64]:
arr = np.arange(1,11)
print(arr)

arr_copy = arr.copy()
arr_copy[:] = 100

print(arr_copy)
print(arr) #Se mantiene el original!!!

[ 1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100]
[ 1  2  3  4  5  6  7  8  9 10]


### <a name="markdown36"></a> Condiciones:
[Indice](#markdown100)

In [67]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [69]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[(arr>5) & (arr<9)] 

array([6, 7, 8], dtype=int8)

In [73]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [75]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

### <a name="markdown37"></a> Operaciones:
[Indice](#markdown100)

#### Con una lista de Python No multiplica cada valor por 2, sino que duplica la lista

In [77]:
py_list = [1,2]
py_list * 2 

[1, 2, 1, 2]

#### Con numpy si podemos hacerlo

In [83]:
arr = np.arange(0,10)
arr_01 = arr.copy()
print(arr)
print(arr_01*2)
print(arr_01+2)
print(1/arr) #No detuvo la ejecución, pero si lanzó una advertencia de 1/0

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_585/2374450473.py:6: RuntimeWarning: divide by zero encountered in divide
  print(1/arr) #No detuvo la ejecución, pero si lanzó una advertencia de 1/0


In [82]:
print(arr**2)
print(arr + arr_01)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]


In [86]:
matriz = arr.reshape(2,5)
print(matriz)
matriz_01 = matriz.copy()

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [88]:
sum_matriz = matriz + matriz_01
print(sum_matriz)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


### <a name="markdown38"></a> Producto entre Matrices.
[Indice](#markdown100)

In [92]:
prod_matr = np.matmul(matriz, matriz_01.T)
print(prod_matr)
# Forma equivalente:
prod_matr_01 = matriz @ matriz_01.T
print(prod_matr_01)

[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]


### Pandas:
[Indice Pandas](#markdown1000)

#### Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos. El nombre viene de “Panel data”.

* Velocidad
* Poco código
* Múltiples formatos de archivos
* Alineación inteligente

### <a name="markdown39"></a> Pandas Series.
[Indice Pandas](#markdown1000)

#### Es muy parecido a un array de una dimensión (o vector) de NumPy.

* Arreglo unidimensional indexado --> El índice comienza en "1".
* Búsqueda por índice
* Slicing
* Operaciones aritméticas
* Distintos tipos de datos

### <a name="markdown40"></a> Creando lista con índices específicos
[Indice Pandas](#markdown1000)

In [3]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
dict = {1: 'Navas', 7: 'Mbappe', 10: 'Neymar', 30:'Messi'}
pd.Series(dict)

### <a name="markdown41"></a> Pandas DataFrame
[Indice Pandas](#markdown1000)
#### Muy parecido a las estructuras matriciales trabajadas con NumPy.

* Estructura principal
* Arreglo de dos dimensiones
* Búsqueda por índice (columnas (uso el nombre) o filas (inicia en 0 hasta la última)), 
* Slicing
* Operaciones aritméticas
* Distintos tipos de datos
* Tamaño variable

### <a name="markdown42"></a> Creando una structura matricial con diccionarios.
[Indice Pandas](#markdown1000)

In [7]:
dict = {
    'Jugador':['Navas','Mbappe','Neymar','Messi'],
    'Altura':[183.0, 170.0, 170.0, 163.0],
    'Goles':[2, 200, 150, 500]
}

In [15]:
df_players = pd.DataFrame(dict, index=[1,7,10,30]) # si no usamos el index usa el default.
display(df_players)

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    150
30   Messi   163.0    500

In [14]:
df_players.index

Int64Index([1, 7, 10, 30], dtype='int64')