## <a name="markdown100"></a> Indice Numpy:
[Numpy](#markdown1)

[¿Por qué Pandas?](#markdown2)

[Formas de importarlas:](#markdown3)

[Slicing List](#markdown0)

[ Sclicing Matrix:](#markdown4)

[Tipos de datos](#markdown5)

[Dimensiones en los datos](#markdown6)

[Agregar o Eliminar dimensiones](#markdown7)

[Expandir dimensiones](#markdown8)

[Remover/comprimir las dimensiones que no están siendo usadas.](#markdown9)

[Creando Arrays con **NumPy**](#markdown10)

[Creando listas solo con ceros](#markdown11)

[Creando Matrices solo con ceros](#markdown12)

[Creando Matrices solo con unos.](#markdown13)

[Creando listas con valores equidistantes entre ellos](#markdown14)

[Matríz Identidad](#markdown15)

[Valores Aleatoreos "un valor"](#markdown16)

[Valores Aleatoreos "una lista de valores"](#markdown17)

[Valores Aleatoreos "una matriz de valores"](#markdown18)

[Valores Aleatoreos "Enteros"](#markdown19)

[Shape](#markdown20)

[Reshape](#markdown21)

[Funciones Principales de NumPy](#markdown22)

[Devuelve el máx número por columna](#markdown23)

[Devuelve el máx número por fila](#markdown24)

[ptp(), pico a pico](#markdown25)

[Percentile()](#markdown26)

[sort()](#markdown27)

[median()](#markdown28)

[median() con Matrices](#markdown29)

[Desviación std()](#markdown30)

[Varianza var()](#markdown31)

[La Media mean()](#markdown32)

[Concatenar concatenate()](#markdown33)

[Transpuesta](#markdown34)

[copy()](#markdown35)

[Condiciones](#markdown36)

[Operaciones](#markdown37)

[Producto entre Matrices](#markdown38)

## <a name="markdown1000"></a> Indice Pandas:

[Series](#markdown39)

[Creando lista con índices específicos](#markdown40)

[Creando una structura matricial con diccionarios](#markdown41)

# Numpy
* Cálculo numérico
* Manejo de Arrays.

# pandas:
* Manipulación y análisis de datos.
# <a name="markdown1"></a> ¿Por qué Numpy?
* Es una librería enfocada al cálculo numérico y manejo de Arrays.

* Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
* Optimiza el almacenamiento en memoria.
* Maneja distintos tipos de datos.
* Es una librería muy poderosa, se pueden crear redes neuronales desde cero.

# <a name="markdown2"></a> ¿Por qué Pandas?
* Pandas está enfocada a la manipulación y análisis de datos.

* Al estar construido sobre NumPy es veloz.
* Requiere poco código para manipular los datos.
* Soporta múltiples formatos de archivos.
* Ordena los datos en una alienación inteligente.
* Se pueden manejar grandes cantidades de datos, hacer analítica y generar dashboards.
* Anilisis inteligente.

#### El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a través del indexado, a un dato específico o un grupo de muchos datos específicos.

# <a name="markdown3"></a> Formas de importarlas:
[Indice](#markdown100)

In [1]:
import numpy as np
import pandas as pd

In [ ]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]

#Volvemos nuestra lista, un array
arr = np.array(lista)

In [2]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)

In [3]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### <a name="markdown0"></a> Slicing List
[Indice](#markdown100)

In [12]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista = np.array(lista)
print(lista[1:6])
print(lista[:6])
print(lista[2:])
print(lista[::3])
print(lista[-1])
print(lista[-3])

[2 3 4 5 6]
[1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[1 4 7]
9
7


### <a name="markdown4"></a>  Sclicing Matrix:
[Indice](#markdown100)

In [16]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix)
print(matrix)
print("*"*15)
print(matrix[1:]) #Desde la fila 1 en adelante.
print("*"*15)
print(matrix[1:,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***************
[[4 5 6]
 [7 8 9]]
***************
[[4 5]
 [7 8]]


* **matrix[fila, columna]** --> devuelve el valor en esa fila intersección esa columna

### <a name="markdown5"></a> Tipos de datos
### [Tipos de datos numpy](https://numpy.org/doc/stable/user/basics.types.html):
[Indice](#markdown100)

In [17]:
arr = np.array([1, 2, 3, 4])
arr.dtype #Muestra el tipo de dato de los componenetes de array.

dtype('int64')

In [18]:
arr = np.array([1, 2, 3, 4], dtype='float64') #Cambiamos el tipo de dato!!!
arr.dtype

dtype('float64')

In [20]:
arr = np.array([1, 2, 3, 4]) # type int64
arr = arr.astype(np.float64) # otra forma de cambiar el tipo de dato.
arr.dtype

dtype('float64')

* En términos de resultado final, no hay diferencia entre las dos formas de cambiar el tipo de datos de un arreglo NumPy. Ambas líneas de código logran el mismo resultado: cambiar el tipo de datos del arreglo arr a float64.

* La diferencia radica en el enfoque utilizado para realizar la conversión:

* En la primera línea de código, se especifica el tipo de datos deseado directamente al crear el arreglo mediante el argumento dtype='float64'. Esto significa que el arreglo se crea inicialmente con el tipo de datos especificado.

* En la segunda línea de código, se utiliza el método astype() de NumPy para realizar la conversión explícita del tipo de datos del arreglo. El método astype() toma como argumento el tipo de datos al que se desea convertir el arreglo.
También se podría definir como sigue:
```python
arr = [1, 2, 3, 4]
arr = np.array(arr, dtype='float64') #Cambiamos el tipo de dato!!!
arr.dtype
```

In [25]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_) #Cambiando a Booleano!!!
arr

array([False,  True,  True,  True,  True])

In [28]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_) #Cambiando a Booleano!!!
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [29]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8) #Cambiando a Booleano!!!
arr

array([0, 1, 2, 3, 4], dtype=int8)

### <a name="markdown6"></a> Dimensiones en los datos:
[Indice](#markdown100)
* **Scalar: 0 Un solo dato o valor --> 2 o "r", un solo valor.**
```python
scalar = np.array(42)
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Vector: Listas de Python --> [1,2,3,4]**
```python
scalar = np.array([1,2,3,4])
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Matriz: Hoja de cálculo --> algo que tenga 2 dimensiones (fila, columna).**
```python
scalar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(scalar) 
scalar.ndim #muestra las dimensiones.
```
* **Tensor: Series de tiempo o Imágenes**
![tensor](https://static.platzi.com/media/articlases/Images/tensor.JPG)
```python
tensor = np.array([
    [
        [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]
    ],
    [
        [13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]
    ]
]) #Matríz 4x3 en la primer posición, matríz 4x3 en la segunda posición.
print(tensor)
tensor.ndim
```
* **Nota, el tensor tiene tres dimensiones**: 
* la primera dimensión corresponde a las dos matrices internas. 
* La segunda dimensión corresponde a las filas de cada matriz.
* La tercera dimensión corresponde a las columnas de cada matriz.

In [13]:
tensor = np.array([
                        [        
                            [
                                [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]
                            ],
                            [
                                [13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]
                            ]
                        ]
                    ]) #Matríz 4x3 en la primer posición, matríz 4x3 en la segunda posición.
print(tensor)
tensor.ndim # Con 4 dimensiones.

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[13 13 15]
   [16 17 18]
   [19 20 21]
   [22 23 24]]]]


4

### <a name="markdown7"></a>  Agregar o eliminar dimensiones
[Indice](#markdown100)
* Se puede definir el número de dimensiones desde la declaración del array

In [16]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

### <a name="markdown8"></a>  Expandir dimensiones
[Indice](#markdown100)
* Se pueden expandir dimensiones a los array ya existentes con expand_dims(). Axis = 0 hace referencia a las filas, mientras que axis = 1 a las columnas.

In [14]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [15]:
expand = np.expand_dims(np.array([1, 2, 3]), axis = 1)
print(expand)
expand.ndim 

[[1]
 [2]
 [3]]


2

### <a name="markdown9"></a>  Remover/comprimir las dimensiones que no están siendo usadas.
[Indice](#markdown100)

In [18]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


### <a name="markdown10"></a>  Creando Arrays con **numpy**
[Indice](#markdown100)
* Numpy nos da varios métodos muy eficientes para poder crear arrays desde 0.

* Este método de NumPy nos permite generar arrays sin definir previamente una lista

In [20]:
# forma tradicional con python.
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
# numpy
list_01 = np.arange(1,10)
print(list_01)
list_02 = np.arange(1,10,2) # De 2 en 2
print(list_02)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### <a name="markdown11"></a>  Creando listas solo con ceros
[Indice](#markdown100)

In [25]:
np.zeros(3)

array([0., 0., 0.])

### <a name="markdown12"></a> Creando Matrices solo con ceros.
[Indice](#markdown100)

In [27]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### <a name="markdown13"></a>  Creando Matrces solo con unos.
[Indice](#markdown100)

In [28]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### <a name="markdown14"></a> Crea listas con valores equidistantes entre ellos.
[Indice](#markdown100)
* Sintaxis:
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
* **start:** Es el valor inicial del rango.
* **stop:** Es el valor final del rango.
* **num:** Es el número de elementos que se generarán en el arreglo. Por defecto es 50.
* **endpoint:** Un valor booleano que indica si el valor final está incluido en el arreglo. Si es True, el valor final está incluido; si es False, el valor final no está incluido. Por defecto es True.
* **retstep:** Un valor booleano que indica si se debe retornar el espaciado entre los valores del arreglo. Si es True, se retorna el arreglo y el espaciado; si es False, solo se retorna el arreglo. Por defecto es False.
* **dtype:** El tipo de dato de los elementos en el arreglo. Por defecto es None, lo que significa que se utilizará el tipo de dato por defecto de NumPy.

In [35]:
values = np.linspace(0,10,num=12, retstep=True)# desde 0 hasta 10 con 12 valores
print(values)

(array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ]), 0.9090909090909091)


### <a name="markdown15"></a>  Matriz identidad
[Indice](#markdown100)
* El comando eye es una función de NumPy que se utiliza para crear una matriz identidad. Una matriz identidad es una matriz cuadrada en la que todos los elementos de la diagonal principal son iguales a 1 y los demás elementos son iguales a 0.

* La sintaxis general de eye es la siguiente:
```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```
* **N:** Es el número de filas de la matriz.
* **M:** (Opcional) Es el número de columnas de la matriz. Si no se especifica, se asume que M=N, por lo que la matriz será cuadrada.
* **k:** (Opcional) Es el desplazamiento de la diagonal principal. Un valor positivo indica una diagonal por encima de la diagonal principal, y un valor negativo indica una diagonal por debajo de la diagonal principal. Por defecto, k=0 y la diagonal principal estará compuesta de unos.
* **dtype:** (Opcional) El tipo de dato de los elementos en la matriz. Por defecto, es un tipo de dato flotante (float).
* **order:** (Opcional) Especifica el orden en que se almacenan los elementos en la matriz. Puede ser 'C' (por filas) o 'F' (por columnas). Por defecto, es 'C'.

In [36]:
matriz_identidad = np.eye(3)

print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### <a name="markdown16"></a> Valores Aleatoreos "un valor":
[Indice](#markdown100)

In [37]:
np.random.rand()

0.6507831363398214

### <a name="markdown17"></a> Valores Aleatoreos "una lista de valores":
[Indice](#markdown100)

In [38]:
np.random.rand(4)

array([0.58510919, 0.11935745, 0.40646536, 0.49571867])

### <a name="markdown18"></a> Valores Aleatoreos "una Matríz de valores":
[Indice](#markdown100)

In [39]:
np.random.rand(2,3)

array([[0.56556431, 0.77719616, 0.71526729],
       [0.61868235, 0.6897348 , 0.36030092]])

### <a name="markdown19"></a>  Valores Aleatoreos "Enteros":
[Indice](#markdown100)
```python
numpy.random.randint(low, high=None, size=None, dtype=int)
```
* **low:** es el límite inferior del rango (inclusive).
* **high:** es el límite superior del rango (exclusivo). Si no se proporciona, se asume que es el límite superior y el límite inferior se establece en 0.
* **size:** es la forma o dimensiones del array que se desea generar. Puede ser un número entero para generar un único número aleatorio o una tupla de enteros para generar un array multidimensional. Si no se proporciona, se devuelve un único número entero.
* **dtype:** es el tipo de datos de los elementos generados. Por defecto, se utiliza int.

In [40]:
np.random.randint(1,15)

6

In [41]:
np.random.randint(1,100,(10,10))

array([[44, 73, 76, 79, 83, 57, 42, 51, 41, 55],
       [29, 83, 71, 53, 55, 30, 74, 84, 17, 16],
       [70, 20, 74, 39, 51, 59,  7, 82, 13, 71],
       [25, 79, 36, 90,  1, 24, 61, 16, 75,  2],
       [71, 55, 90, 78, 78, 90, 38, 71, 16, 11],
       [81, 62, 42, 92, 74, 56,  6, 14, 10, 13],
       [72, 11, 98, 57, 26, 76, 64, 90, 36, 39],
       [82, 52, 14, 10, 29, 46, 28, 41, 14, 50],
       [88, 59, 25, 92, 30, 50, 10, 29, 12, 73],
       [14, 74, 36, 35, 62,  3, 82, 15, 16, 38]])

### <a name="markdown20"></a>  Shape:
[Indice](#markdown100)
* Forma del arreglo.

In [44]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.shape # retorna la forma, en este caso una matríz de 3x2

[[6 2]
 [3 8]
 [3 4]]


(3, 2)

### <a name="markdown21"></a> Reshape:
[Indice](#markdown100)
* Cambia la forma del arreglo.
```python
numpy.reshape(array, newshape, order='C')
```
* **array:** El array original que se desea redimensionar.
* **newshape:** La nueva forma que se desea dar al array. Puede ser especificada como una tupla de enteros o como una lista de enteros separados por comas. Es importante tener en cuenta que la cantidad total de elementos en el array original debe ser igual a la cantidad total de elementos en el nuevo array.
* **order (opcional):** Especifica el orden en que se deben leer los elementos del array original para reorganizarlos en el nuevo array. Los posibles valores son 'C' (orden C-contiguo, por defecto), 'F' (orden Fortran-contiguo), o 'A' (lo ordena según la mejor performance del computador).

#### Nota: los parámetros 'C' y 'F' se refieren al orden en el que los elementos del array original se almacenan en la memoria.

#### 'C' hace referencia al estilo de orden C-contiguo, también conocido como orden de fila principal (row-major order) o almacenamiento en el estilo C. En este orden, los elementos de una matriz bidimensional se almacenan por filas, es decir, los elementos de una misma fila se almacenan de forma contigua en la memoria. Este es el orden por defecto en NumPy.
![C-style contiguous segment](https://static.platzi.com/media/user_upload/Apilar%20por%20filas%20V-ca01870a-aaaf-4bdb-8203-6885bd220f20.jpg)
#### 'F' se refiere al estilo de orden Fortran-contiguo, también conocido como orden de columna principal (column-major order) o almacenamiento en el estilo Fortran. En este orden, los elementos de una matriz bidimensional se almacenan por columnas, es decir, los elementos de una misma columna se almacenan de forma contigua en la memoria.
![Fortran-style contiguous segment](https://static.platzi.com/media/user_upload/Apilar%20por%20Columnas-0b5370fe-2271-4d55-bd10-5b290114678b.jpg)
#### La diferencia entre ambos órdenes radica en cómo se accede a los elementos de la matriz en la memoria. Al trabajar con arrays multidimensionales grandes, el orden de almacenamiento puede afectar el rendimiento y la eficiencia del acceso a los elementos.

#### En la mayoría de los casos, el orden 'C' es utilizado por defecto y es adecuado para la mayoría de las operaciones y algoritmos. Sin embargo, en algunos casos particulares, como cuando se trabaja con operaciones lineales algebraicas o algoritmos específicos que requieren un acceso eficiente por columnas, se puede utilizar el orden 'F'.

#### Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en A.

In [47]:
arr = np.random.randint(1,10,(3,2))
print(arr)
arr.reshape(1,6) # 1x6, está límitado por la cantidad de valores individuales.

[[3 2]
 [8 5]
 [6 4]]


array([[3, 2, 8, 5, 6, 4]])

In [48]:
np.reshape(arr,(1,6)) #otra forma equivalente y válida.

array([[3, 2, 8, 5, 6, 4]])

In [50]:
np.reshape(arr,(2,3), 'C')

array([[3, 2, 8],
       [5, 6, 4]])

In [51]:
np.reshape(arr,(2,3), 'F')

array([[3, 6, 5],
       [8, 2, 4]])

In [52]:
np.reshape(arr,(2,3), 'A')

array([[3, 2, 8],
       [5, 6, 4]])

### <a name="markdown22"></a> Funciones Principales de NumPy:
[Indice](#markdown100)

In [55]:
arr = np.random.randint(1,20,10)
arr

array([19, 16, 14,  7,  9,  8,  5, 19, 18, 12])

In [56]:
matriz = arr.reshape(2,5)
matriz

array([[19, 16, 14,  7,  9],
       [ 8,  5, 19, 18, 12]])

In [57]:
np.max(arr) #arr.max() también funciona.

19

In [58]:
np.max(matriz) #matriz.max() también funciona.

19

### <a name="markdown23"></a>  Devuelve el máx número por columna.
[Indice](#markdown100)
* matriz.max(0) también funciona.

In [60]:
np.max(matriz, 0) 

array([19, 16, 19, 18, 12])

### <a name="markdown24"></a>  Devuelve el máx número por fila.
[Indice](#markdown100)
* matriz.max(1) también funciona.

In [61]:
np.max(matriz, 1)

array([19, 19])

#### También tenemos .argmax() que nos devuelve la posición del Máx. elemento

In [64]:
arr = np.random.randint(1,20,10)
print(arr)
arr.argmax()

[11  8  5  6  7 12 15  7  8  1]


6

In [67]:
matriz = arr.reshape(2,5)
print(matriz)
matriz.argmax(0)

[[11  8  5  6  7]
 [12 15  7  8  1]]


array([1, 1, 1, 1, 0])

In [68]:
matriz.argmax(1)

array([0, 1])

#### Nota: Funcionamiento contrario remplazando "max" por "min"

### <a name="markdown25"></a> ptp(), pico a pico:
[Indice](#markdown100)
* Devuelve la diferencia entre Máx y Mín.

In [70]:
arr = np.random.randint(1,20,10)
arr

array([16, 14, 14,  6,  3,  6,  8, 14,  5, 18])

In [71]:
arr.ptp()

15

### <a name="markdown26"></a> Percentile()
[Indice](#markdown100)
* La función np.percentile() en NumPy se utiliza para calcular los percentiles de un conjunto de datos. Un percentil es un valor que indica la posición relativa de un dato dentro de un conjunto, es decir, el porcentaje de datos que se encuentran por debajo de ese valor.

* La sintaxis básica de la función np.percentile() es la siguiente:
```python
np.percentile(data, q, axis=None)
```
* **data:** Es el conjunto de datos del cual se desea calcular el percentil.
* **q:** Es el percentil o lista de percentiles que se desean calcular. Puede ser un solo valor o una lista de valores.
* **axis:** Es un parámetro opcional que indica a lo largo de qué eje se deben calcular los percentiles en el caso de arrays multidimensionales. Por defecto, se calculan los percentiles en todo el array.
La función np.percentile() devuelve el valor del percentil o una lista de valores si se pasó una lista de percentiles como parámetro q.

#### Nota: El percentil es una medida de posición usada en estadística que indica, una vez ordenados los datos de menor a mayor, el valor de la variable por debajo del cual se encuentra un porcentaje dado de observaciones en un grupo. Por ejemplo, el percentil 20 es el valor bajo el cual se encuentran el 20 % de las observaciones, y el 80 % restante son mayores.


In [4]:
arr = np.random.randint(1,100,10)
arr

array([82, 46, 42, 97, 89, 81, 49, 38, 93, 27])

In [8]:
percentil = np.percentile(arr,50)
percentil

65.0

In [14]:
arr_01 = [1,2,3,4,5,6,7,8,9,10]

per_0 = np.percentile(arr_01,0)
per_50 = np.percentile(arr_01,50)
per_100 = np.percentile(arr_01,100)
print(per_0, per_50, per_100)

1.0 5.5 10.0


### <a name="markdown27"></a> sort():
[Indice](#markdown100)
* ordena de menor a mayor.
```python
arr = arr.sort()
```

### <a name="markdown28"></a> median():
[Indice](#markdown100)
* Entrega la mediana, el valor que está en la mitad.

In [16]:
arr = np.random.randint(1,100,20)
print(arr)
med = np.median(arr)
print(med)

[14 38 59 13 10 25 24 97 94 57 41 32 41 63 97 93 10 83 97 78]
49.0


### <a name="markdown29"></a> median() con Matrices:
[Indice](#markdown100)

In [23]:
matrix = np.reshape(arr,(2,10))
print(matrix)

med_mat_col = np.median(matrix,0) #Por Columnas.
print(f'by col: {med_mat_col}')

med_mat_row = np.median(matrix,1)
print(f'by row: {med_mat_row}')

[[14 38 59 13 10 25 24 97 94 57]
 [41 32 41 63 97 93 10 83 97 78]]
by col: [27.5 35.  50.  38.  53.5 59.  17.  90.  95.5 67.5]
by row: [31.5 70.5]


### <a name="markdown30"></a> Desviación std():
[Indice](#markdown100)

In [24]:
arr = np.random.randint(1,100,20)
dsta = np.std(arr)
print(dsta)

29.583610327341724


### <a name="markdown31"></a> Varianza var()
[Indice](#markdown100)

In [34]:
arr = np.random.randint(1,100,20)
var = np.var(arr)

#Nota, la var = dsta**2
dsta = np.std(arr)
var_01 = dsta**2 #La varianza = al cuadrado de la desv std.
print(f'var: {var}, dsta: {dsta}, dsta**2: {var_01}')

var: 940.6899999999998, dsta: 30.670670028546812, dsta**2: 940.6899999999997


### <a name="markdown32"></a> La Media mean()
[Indice](#markdown100)
* Es el promedio.
```python
arr = np.mean(arr)
```

### <a name="markdown33"></a> Concatenar concatenate()
[Indice](#markdown100)

In [40]:
a = np.array([[1,2],[3,4]])
print(a)
b = np.array([5,6]) # Tiene dim: 1
print(b)

[[1 2]
 [3 4]]
[5 6]


#### **Tienen que tener las mismas dimensiones**

In [37]:
b_exp_col = np.expand_dims(b, axis=0)
b_exp_row = np.expand_dims(b, axis=1)

print(b_exp_col, f'dim: {b_exp_col.ndim}')
print(b_exp_row, f'dim: {b_exp_row.ndim}')

[[5 6]] dim: 2
[[5]
 [6]] dim: 2


#### **A concatenar por columnas:**

In [38]:
conc_col = np.concatenate((a,b_exp_col), axis=0)
conc_col

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Concatenamos por filas:

In [43]:
conc_col = np.concatenate((a,b_exp_row), axis=1)
conc_col

array([[1, 2, 5],
       [3, 4, 6]])

### <a name="markdown34"></a> Transpuesta T:
[Indice](#markdown100)
* ejemplo pasa de 3x2 --> 2x3

In [45]:
a = np.array([[1,2],[3,4]])
print(a)
a_transp = a.T
print(a_transp)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


### Entonces podemos utilizar para concatenar

In [47]:
conc_col = np.concatenate((a,b_exp_col.T), axis=1) #Sin la "T" da error, y nos da igual que b_exp_row
conc_col

array([[1, 2, 5],
       [3, 4, 6]])

### <a name="markdown35"></a> copy():
[Indice](#markdown100)
* Uno de los problemas más comunes es manipular una variable y modificarla, tal como se observa en el siguiente ejemplo.

In [60]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [59]:
arr_cuted_01 = arr[0:6]
print(arr_cuted_01)

arr_cuted_01[:] = 0 #todos los valores en 0.
print(arr_cuted_01)

print(arr) #Se ve el cambio a la variable original

[1 2 3 4 5 6]
[0 0 0 0 0 0]
[ 0  0  0  0  0  0  7  8  9 10]


#### Solución a Copy:

In [64]:
arr = np.arange(1,11)
print(arr)

arr_copy = arr.copy()
arr_copy[:] = 100

print(arr_copy)
print(arr) #Se mantiene el original!!!

[ 1  2  3  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100]
[ 1  2  3  4  5  6  7  8  9 10]


### <a name="markdown36"></a> Condiciones:
[Indice](#markdown100)

In [67]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [69]:
cond_index = arr > 5
cond_index

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[(arr>5) & (arr<9)] 

array([6, 7, 8], dtype=int8)

In [73]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [75]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

### <a name="markdown37"></a> Operaciones:
[Indice](#markdown100)

#### Con una lista de Python No multiplica cada valor por 2, sino que duplica la lista

In [77]:
py_list = [1,2]
py_list * 2 

[1, 2, 1, 2]

#### Con numpy si podemos hacerlo

In [83]:
arr = np.arange(0,10)
arr_01 = arr.copy()
print(arr)
print(arr_01*2)
print(arr_01+2)
print(1/arr) #No detuvo la ejecución, pero si lanzó una advertencia de 1/0

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_585/2374450473.py:6: RuntimeWarning: divide by zero encountered in divide
  print(1/arr) #No detuvo la ejecución, pero si lanzó una advertencia de 1/0


In [82]:
print(arr**2)
print(arr + arr_01)

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]


In [86]:
matriz = arr.reshape(2,5)
print(matriz)
matriz_01 = matriz.copy()

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [88]:
sum_matriz = matriz + matriz_01
print(sum_matriz)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


### <a name="markdown38"></a> Producto entre Matrices.
[Indice](#markdown100)

In [92]:
prod_matr = np.matmul(matriz, matriz_01.T)
print(prod_matr)
# Forma equivalente:
prod_matr_01 = matriz @ matriz_01.T
print(prod_matr_01)

[[ 30  80]
 [ 80 255]]
[[ 30  80]
 [ 80 255]]


### Pandas:
[Indice Pandas](#markdown1000)

#### Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos. El nombre viene de “Panel data”.

* Velocidad
* Poco código
* Múltiples formatos de archivos
* Alineación inteligente

### <a name="markdown39"></a> Pandas Series.
[Indice Pandas](#markdown1000)

#### Es muy parecido a un array de una dimensión (o vector) de NumPy.

* Arreglo unidimensional indexado --> El índice comienza en "1".
* Búsqueda por índice
* Slicing
* Operaciones aritméticas
* Distintos tipos de datos

### <a name="markdown40"></a> Creando lista con índices específicos
[Indice Pandas](#markdown1000)

In [3]:
psg_players = pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
dict = {1: 'Navas', 7: 'Mbappe', 10: 'Neymar', 30:'Messi'}
pd.Series(dict)

### <a name="markdown41"></a> Pandas DataFrame
[Indice Pandas](#markdown1000)
#### Muy parecido a las estructuras matriciales trabajadas con NumPy.

* Estructura principal
* Arreglo de dos dimensiones
* Búsqueda por índice (columnas (uso el nombre) o filas (inicia en 0 hasta la última)), 
* Slicing
* Operaciones aritméticas
* Distintos tipos de datos
* Tamaño variable

### <a name="markdown42"></a> Creando una structura matricial con diccionarios.
[Indice Pandas](#markdown1000)

In [7]:
dict = {
    'Jugador':['Navas','Mbappe','Neymar','Messi'],
    'Altura':[183.0, 170.0, 170.0, 163.0],
    'Goles':[2, 200, 150, 500]
}

In [15]:
df_players = pd.DataFrame(dict, index=[1,7,10,30]) # si no usamos el index usa el default.
display(df_players)

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    150
30   Messi   163.0    500

In [14]:
df_players.index

Int64Index([1, 7, 10, 30], dtype='int64')

### <a name="markdown43"></a> Leyendo CSV:
[Indice Pandas](#markdown1000)

#### Sintaxis:
```python
df = pd.read_csv(filepath_or_buffer, sep=',', header='infer', names=None, ...)
```
Aquí hay una explicación de algunos de los parámetros más comunes de la función:

* **filepath_or_buffer:** Especifica la ubicación del archivo CSV que se va a leer. Puede ser una cadena de ruta de archivo o una URL.
* **sep:** Especifica el delimitador utilizado en el archivo CSV para separar las columnas. Por defecto, se utiliza la coma (,), pero se puede cambiar a otro carácter, como punto y coma (;), tabulación (\t), etc.
* **header:** Especifica la fila que contiene los nombres de las columnas. Por defecto, se toma la primera fila como encabezado (header='infer'), pero también se puede establecer en None si el archivo CSV no tiene una fila de encabezado.
* **names:** Permite proporcionar una lista de nombres de columnas personalizados en caso de que el archivo CSV no tenga una fila de encabezado.
* **Otros parámetros:** La función read_csv() también admite muchos otros parámetros, como dtype para especificar el tipo de datos de las columnas, na_values para manejar los valores nulos, parse_dates para analizar columnas como fechas, entre otros.

### Sintaxis Completa:
```python
df = pd.read_csv(
    filepath_or_buffer,  # Ruta del archivo CSV o una URL.
    sep=',',  # Delimitador utilizado en el archivo CSV para separar las columnas.
    delimiter=None,  # Delimitador adicional, si se necesita usar otro diferente al especificado en 'sep'.
    header='infer',  # Fila que contiene los nombres de las columnas. Por defecto, se toma la primera fila como encabezado.
    names=None,  # Lista de nombres de columnas personalizados en caso de que el archivo CSV no tenga una fila de encabezado.
    index_col=None,  # Nombre de columna o índice de columna para usar como índice de fila del DataFrame resultante.
    usecols=None,  # Lista de columnas a leer del archivo CSV.
    squeeze=False,  # Si se establece en True y el archivo CSV contiene solo una columna, se devuelve una Serie en lugar de un DataFrame.
    prefix=None,  # Prefijo a agregar a los nombres de las columnas si no hay encabezado.
    mangle_dupe_cols=True,  # Renombrar las columnas duplicadas si es necesario.
    dtype=None,  # Tipo de datos de las columnas.
    engine=None,  # Motor de análisis a utilizar. Por defecto, se selecciona automáticamente según la extensión del archivo.
    converters=None,  # Diccionario de funciones para convertir valores en determinadas columnas.
    true_values=None,  # Lista de valores que se considerarán verdaderos.
    false_values=None,  # Lista de valores que se considerarán falsos.
    skiprows=None,  # Número de filas a omitir desde el comienzo del archivo CSV.
    nrows=None,  # Número máximo de filas a leer desde el archivo CSV.
    skip_blank_lines=True,  # Omitir las líneas en blanco.
    na_values=None,  # Lista de valores que se considerarán como valores nulos.
    keep_default_na=True,  # Mantener los valores por defecto que se consideran como valores nulos.
    na_filter=True,  # Detectar y convertir los valores nulos.
    verbose=False,  # Mostrar mensajes informativos durante la lectura del archivo.
    skipinitialspace=False,  # Omitir espacios iniciales en las columnas.
    skipfooter=0,  # Número de filas al final del archivo a omitir.
    nrows=None,  # Número máximo de filas a leer desde el archivo CSV.
    quotechar='"',  # Carácter utilizado para citar campos.
    quoting=csv.QUOTE_MINIMAL,  # Controla cuándo se citan los campos.
    doublequote=True,  # Controla si se permite el uso de comillas dentro de los campos citados.
    escapechar=None,  # Carácter de escape utilizado cuando se especifica `quoting` como QUOTE_NONE.
    comment=None,  # Carácter que indica el inicio de un comentario en el archivo CSV.
    encoding=None,  # Codificación utilizada para leer el archivo CSV.
    dialect=None,  # Clase dialecto de CSV personalizado para el análisis.
    error_bad_lines=True,  # Controla el comportamiento cuando se encuentran líneas inválidas.
    warn_bad_lines=True,  # Mostrar advertencias cuando)
```

In [3]:
df_books = pd.read_csv('bestsellers-with-categories.csv')
display(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

### Agregando parámetros:

In [5]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [9]:
df_books = pd.read_csv('bestsellers-with-categories.csv', sep=',', header=0, names=['BookName', 'BookAuthor', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])
display(df_books)

BookName  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                   BookAuthor  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

### <a name="markdown44"></a> Leyendo JSON:
[Indice Pandas](#markdown1000)

### Sintaxis:
```python
df = pd.read_json(
    path_or_buf,  # Ruta del archivo JSON o un objeto con contenido JSON.
    orient=None,  # Orientación de los datos. Puede ser 'split', 'records', 'index', 'columns' o 'values'.
    typ='frame',  # Define el tipo de objeto a crear. Por defecto, se crea un DataFrame, pero también puede ser 'series' para crear una Serie.
    dtype=True,  # Controla si se infieren los tipos de datos de las columnas automáticamente.
    convert_axes=True,  # Controla si se convierten los ejes del objeto JSON.
    convert_dates=True,  # Controla si se convierten las fechas automáticamente.
    keep_default_dates=True,  # Controla si se mantienen las fechas por defecto en caso de errores de conversión.
    numpy=False,  # Controla si los objetos JSON se convierten en arrays NumPy.
    precise_float=False,  # Controla si se utiliza una representación precisa de los números de punto flotante.
    date_unit=None,  # Unidad de tiempo para las fechas. Puede ser 's', 'ms', 'us' o 'ns'.
    encoding=None,  # Codificación utilizada para leer el archivo JSON.
    lines=False,  # Indica si el archivo JSON contiene una serie de objetos JSON separados por líneas.
    chunksize=None,  # Tamaño de los fragmentos para leer el archivo JSON de forma incremental.
    compression='infer',  # Método de compresión utilizado. Por defecto, se infiere automáticamente.
    nrows=None,  # Número máximo de filas a leer del archivo JSON.
    json_module=None,  # Módulo personalizado a utilizar para el análisis JSON.
)
```

In [14]:
df_json = pd.read_json('hpcharactersdataraw.json')
display(df_json)

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

In [15]:
df_json = pd.read_json('hpcharactersdataraw.json', typ='Series')
display(df_json)

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

###### <a name="markdown45"></a> Selectionando filas con slicing:
[Indice Pandas](#markdown1000)

In [16]:
df_books[0:4]

BookName          BookAuthor  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

### <a name="markdown46"></a> Selectionando columnas con una lista:
[Indice Pandas](#markdown1000)

In [20]:
df_books[['BookName', 'BookAuthor', 'Price', 'Year']]

BookName  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                   BookAuthor  Price  Year  
0                    JJ Smith      8  2016  
1                Stephen King     22  2011  
2          Jordan B. Peterson     15  2018  
3               George Orwell      6  2017  
4    National Geographic Kids     12  2019  
..                        ...    ...   ...  
545               Jeff Kinney      8  2019  
546               Jen Sincero      8  2016  
547               Jen Sincero      8  2017  
548               Jen Sincero      8  2018  
549               Jen Sincero      8  2019  

[550 rows x 4 columns]

### <a name="markdown47"></a> loc:
[Indice Pandas](#markdown1000)
```python
df.loc[row_indexer, column_indexer]
```
* **row_indexer:** Especifica las etiquetas o condiciones booleanas para las filas que se desean seleccionar. Puede ser un solo valor, una lista, un array NumPy booleano o una expresión booleana.
* **column_indexer:** Especifica las etiquetas o condiciones booleanas para las columnas que se desean seleccionar. Puede ser un solo valor, una lista, un array NumPy booleano o una expresión booleana.

In [22]:
df_books.loc[2]  # Accede a la fila con etiqueta 2

BookName       12 Rules for Life: An Antidote to Chaos
BookAuthor                          Jordan B. Peterson
User Rating                                        4.7
Reviews                                          18979
Price                                               15
Year                                              2018
Genre                                      Non Fiction
Name: 2, dtype: object

In [24]:
df_books.columns

Index(['BookName', 'BookAuthor', 'User Rating', 'Reviews', 'Price', 'Year',
       'Genre'],
      dtype='object')

In [25]:
df_books.loc[2:5, 'User Rating':'Year']  # Accede a las filas 2 a 5 y las columnas 'User Rating' a 'Year'


User Rating  Reviews  Price  Year
2          4.7    18979     15  2018
3          4.7    21424      6  2017
4          4.8     7665     12  2019
5          4.4    12643     11  2011

In [29]:
df_books.loc[df_books['Price'] > 5]  # Filtra las filas donde el valor en 'Price' es mayor a 5

BookName  \
42          Cabin Fever (Diary of a Wimpy Kid, Book 6)   
71             Diary of a Wimpy Kid: Hard Luck, Book 8   
116                        Frozen (Little Golden Book)   
193                               JOURNEY TO THE ICE P   
219                                  Little Blue Truck   
358              The Constitution of the United States   
381                                        The Getaway   
461  The Short Second Life of Bree Tanner: An Eclip...   
505                              To Kill a Mockingbird   
506                              To Kill a Mockingbird   
507                              To Kill a Mockingbird   
508                              To Kill a Mockingbird   

                           BookAuthor  User Rating  Reviews  Price  Year  \
42                        Jeff Kinney          4.8     4505      0  2011   
71                        Jeff Kinney          4.8     6812      0  2013   
116                         RH Disney          4.7     3642      0  2014   
193                         RH Disney          4.6      978      0  2014   
219                    Alice Schertle          4.9     1884      0  2014   
358  Delegates of the Constitutional
          4.8     2774      0  2016   
381                       Jeff Kinney          4.8     5836      0  2017   
461                   Stephenie Meyer          4.6     2122      0  2010   
505                        Harper Lee          4.8    26234      0  2013   
506                        Harper Lee          4.8    26234      0  2014   
507                        Harper Lee          4.8    26234      0  2015   
508                        Harper Lee          4.8    26234      0  2016   

           Genre  
42       Fiction  
71       Fiction  
116      Fiction  
193      Fiction  
219      Fiction  
358  Non Fiction  
381      Fiction  
461      Fiction  
505      Fiction  
506      Fiction  
507      Fiction  
508      Fiction

In [37]:
df_01 = df_books.loc[df_books['Price'] < 1, 'Year'] = 2222  # Asigna el valor 2222 a 'Year' en las filas que cumplen la condición
display(df_books['Price']<1)

0      False
1      False
2      False
3      False
4      False
       ...  
545    False
546    False
547    False
548    False
549    False
Name: Price, Length: 550, dtype: bool

In [38]:
df_books.loc[:, ['Reviews']] * -1 #multiplica por -1 todos los valores de la columna Reviews

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [44]:
df_books.loc[:, ['BookAuthor']] == 'JJ Smith' #muestra la columna Author con True en los valores que cumplen la condicion y False para los que no la cumplen

BookAuthor
0          True
1         False
2         False
3         False
4         False
..          ...
545       False
546       False
547       False
548       False
549       False

[550 rows x 1 columns]

### <a name="markdown48"></a> iloc():
[Indice Pandas](#markdown1000)
* La función iloc() en Pandas se utiliza para acceder y seleccionar datos en un DataFrame mediante índices enteros en lugar de etiquetas. Proporciona una forma de filtrar y manipular datos basándose en posiciones numéricas de filas y columnas.

In [12]:
df_books.iloc[:, 0:3] # quiero todas las filas de las columnas desde 0 a 3

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [13]:
df_books.iloc[1,3]*-1 # multiplica por -1 el valor en intersección fila índice 1 columna índice 3

-2052

In [14]:
df_books.iloc[:2, 2:] # desde la fila desde el inicio al índice 2, y columna índice 2 al final

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

In [15]:
df_books.iloc[2]  # Accede a la tercera fila del DataFrame

Name           12 Rules for Life: An Antidote to Chaos
Author                              Jordan B. Peterson
User Rating                                        4.7
Reviews                                          18979
Price                                               15
Year                                              2018
Genre                                      Non Fiction
Name: 2, dtype: object

In [16]:
df_books.iloc[2:5, 0:3]  # Accede a las filas 3 a 5 y las columnas 1 a 3 del DataFrame


Name  \
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  
2        Jordan B. Peterson          4.7  
3             George Orwell          4.7  
4  National Geographic Kids          4.8

In [17]:
df_books.iloc[2, 3]  # Accede al elemento en la tercera fila y cuarta columna del DataFrame


18979

### <a name="markdown49"></a> Eliminar columnas de un df:
[Indice Pandas](#markdown1000)

In [18]:
df_books.drop('Genre', axis=1) 
'''
axis=0 Filas, axis=1 Columnas, solo lo borra de la salida NO elemina el df original

Para borrarlo directamente desde el df:
df_books.drop('Genre', axis=1, inplace=True)

Tambíen lo borra asociandolo nuevamente al data frame, ej:
df_books = df_books.drop('Genre', axis=1)

Otra forma de borrado directamente desde el df con features the Python:
del def_books['Price']
''' 

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

### <a name="markdown50"></a> Eliminar filas de un df:
[Indice Pandas](#markdown1000)

In [ ]:
df_books.drop(0, axis=0) #borrado de la fila ínidce "0"

In [ ]:
df_books.drop([0,1,2], axis=0) #elimina las filas 0, 1 y 2 del dataFrame

In [ ]:
df_books.drop(range(0,10), axis=0) #elimina las primeras 10 filas del dataFrame

### <a name="markdown51"></a> Agregar columnas a un df:
[Indice Pandas](#markdown1000)

In [20]:
#Crea una nueva columna con el nombre de Nueva_columna de valores Nan
#nan --> valor no numérico.
df_books['Nueva_columna'] = np.nan 
display(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
..             ...  
545            NaN  
546            NaN  
547            NaN  
548            NaN  
549            NaN  

[550 rows x 8 columns]

In [21]:
df_books.shape[0] #Devuelve el número de filas.

550

In [22]:
df_books.shape[1] #Devuelve el número de columnas.

8

In [27]:
total_row_num = df_books.shape[0]
data = np.arange(0, total_row_num)

In [29]:
df_books['range'] = data #Agrego una nueva columna con los valores de data
display(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  range  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

### <a name="markdown52"></a> Agregar filas **append()** a un df:
[Indice Pandas](#markdown1000)

* La función append() en pandas se utiliza para concatenar o unir dos o más DataFrames o Series. Permite agregar filas adicionales a un DataFrame existente.

* La sintaxis básica de la función append() es la siguiente:

```python
df1.append(df2)
```
* La función append() crea un nuevo DataFrame que contiene todas las filas de df1 seguidas de todas las filas de df2. El índice del nuevo DataFrame se mantiene o se reinicia dependiendo del parámetro ignore_index. Si ignore_index=True, se crea un nuevo índice numérico secuencial para el DataFrame resultante. Si ignore_index=False o no se especifica, se conserva el índice original de cada DataFrame.

* Es importante tener en cuenta que la función append() no modifica los DataFrames originales, sino que crea un nuevo DataFrame con las filas adicionales.
```python
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})

df_combined = df1.append(df2)
print(df_combined)
```
* Este código creará un nuevo DataFrame df_combined que contendrá todas las filas de df1 seguidas de todas las filas de df2.

* Es importante tener en cuenta que la función append() puede ser costosa en términos de rendimiento si se utiliza repetidamente para agregar muchas filas a un DataFrame grande. En tales casos, puede ser más eficiente crear una lista de DataFrames y luego usar la función concat() para combinarlos en un solo DataFrame.

### <a name="markdown53"></a> Agregar filas **concat()** a un df:
[Indice Pandas](#markdown1000)

* La función concat() en pandas se utiliza para concatenar o unir dos o más DataFrames a lo largo de un eje específico (por defecto, el eje 0, que representa las filas).

* La sintaxis básica de la función concat() es la siguiente:
```python
pd.concat([df1, df2, df3, ...])
```
* donde df1, df2, df3, etc., son los DataFrames que se desean concatenar.

* La función concat() toma una lista de DataFrames como argumento y devuelve un nuevo DataFrame que contiene la concatenación de los DataFrames de la lista. Los DataFrames se concatenan uno tras otro a lo largo del eje especificado.

* Es posible especificar el eje a lo largo del cual se realiza la concatenación utilizando el parámetro axis. Si axis=0 (o no se especifica), los DataFrames se concatenan a lo largo de las filas, lo que resulta en un DataFrame con más filas. Si axis=1, los DataFrames se concatenan a lo largo de las columnas, lo que resulta en un DataFrame con más columnas.

* Es posible controlar el manejo de los índices de los DataFrames utilizando el parámetro ignore_index. Si ignore_index=True, se crea un nuevo índice numérico secuencial para el DataFrame resultante. Si ignore_index=False (por defecto) o no se especifica, se conservan los índices originales de cada DataFrame.

* Aquí hay un ejemplo de cómo usar la función concat() en pandas:
```python
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'A': [7, 8, 9], 'B': [10, 11, 12]})

df_combined = pd.concat([df1, df2])
print(df_combined)
```
* Este código creará un nuevo DataFrame df_combined que contiene la concatenación de df1 y df2 a lo largo del eje 0 (filas).

* La función concat() también permite especificar otros parámetros, como join para controlar cómo se manejan las columnas que no coinciden entre los DataFrames y keys para agregar claves de nivel superior en el índice resultante.

* En resumen, la función concat() es útil cuando se desea combinar DataFrames en función de un eje específico, ya sea a lo largo de las filas o las columnas.